# Generated by Django 4.2.7 on 2024-06-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
    ]
