# Generated by Django 4.2.7 on 2024-07-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_checkoutproduct_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutproduct',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.checkout'),
            preserve_default=False,
        ),
    ]
